### ISSUE TITLE
Slow performance on parallel Tasks

### ISSUE THREAD

**Issue by karen7272** [BioQwer/Transportation_theory_vs_M_metod#4]
I have application which is divided into two parts.
It starts with single thread, than it creates 8 parallel Tasks.

Running this application on .Net framework 4.6 and .Net Core 2.0 (on the same machine) gives different performance results.

On parallel Tasks .Net Core 2.0 is about 15% slower than .Net Framework 4.6. But on single thread part .Net Core is faster about 5%.

Are there any ways to improve performance of parallel Tasks in .Net Core 2.0 ?

I use the following configuration for my application:

`<PropertyGroup> 
<OutputType>Exe</OutputType> 
<TargetFramework>netcoreapp2.0</TargetFramework>
<Platforms>AnyCPU;x64</Platforms>
<ServerGarbageCollection>true</ServerGarbageCollection> 
</PropertyGroup>`

**Comment by BioQwer** [comment]
Hi, @karen7272 

> On parallel Tasks .Net Core 2.0 is about 15% slower than .Net Framework 4.6. But on single thread part .Net Core is faster about 5%.

Performance test it's very subjectively think, for good result you should execute program about 1000 times as minimum.
In Windows you can chose priority of application, i recommend to chose Realtime priority.  

Are you sure that you don't have problems with algorithm?
It's issues of my repo?
